language: python
sudo: false
python:
- '2.7'
matrix:
  allow_failures:
  - python: '2.6'
  - python: '3.4'
  - python: pypy
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install nose
- pip install flake8
script:
- cd propiedades
- python manage.py test
- flake8 propiedades
after_success: coveralls
os:
- linux
# - osx
notifications:
  slack: labgcba:NXhen9KludVJgXx0Q2AClN23
