language: python
sudo: false
python:
- '2.7'
matrix:
  allow_failures:
  - python: '2.6'
  - python: '3.4'
  - python: pypy
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install nose
- pip install pylint
script:
- nosetests
- pylint propiedades/propiedades
after_success: coveralls
os:
- linux
# - osx
