# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Medium')], max_length=3)),
                ('surface', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Medium')], max_length=3)),
                ('surface', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
