# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 19:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RentListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dolares')], max_length=3)),
                ('surface', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dolares')], max_length=3)),
                ('surface', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
