# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingRent',
            new_name='RentListing',
        ),
        migrations.RenameModel(
            old_name='ListingSale',
            new_name='SaleListing',
        ),
    ]
