# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20151215_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='currency',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dolares')], max_length=3),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='currency',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dolares')], max_length=3),
        ),
    ]
