# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20151215_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='id',
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
