# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='max_surface',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='min_surface',
            field=models.BigIntegerField(null=True),
        ),
    ]
