# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20151214_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='user_id',
            new_name='user',
        ),
    ]
